name: Lint Source Code with golangci-lint-with-reviewdog

on:
  pull_request:
    paths: 
      # mainブランチへのPR時にワークフローを実行する
      - "**.go"
      - ".github/workflows/golangci-lint-with-reviewdog.yaml"

jobs:
  golangci-lint-with-reviewdog:
    strategy:
      fail-fast: false
      matrix:
        go: [1.18, 1.19]

    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.3.0
        
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2.2.2
        with:
          cache: false
          github_token: ${{ github.token }}
          go_version: ${{ matrix.go }}
          golangci_lint_flags: "--exclude-use-default=false --config=./.golangci.yaml ./..."
          golangci_lint_version: v1.51.2
          reporter: "github-pr-review"
